### ISSUE TITLE
backward-ness

### ISSUE THREAD

**Issue by natashabatalha** [ExoCTK/ExoCTKWeb#44]
https://github.com/ExoCTK/ExoCTKWeb/blob/ef6967fe7765664ec41b1cbc3240517ff19b7dde/exoctk_app/app_exoctk.py#L918

`        y=flux_planet[::-1]`

**Comment by julesfowler** [comment]
@natashabatalha We fixed this -- right?

**Comment by natashabatalha** [comment]
Correct
